### ISSUE TITLE
mac package does not contain hb-coretext.h

### ISSUE THREAD

**Issue by scopatz** [conda-forge/harfbuzz-feedstock#45]
CoreText font support is needed for some downstream applications (such as kitty), and it is a mac-only thing.  Perhaps this isn't being compiled with that support.

**Comment by pkgw** [comment]
I will try to look into this, but I have a zillion things to do these days — speedy merger promised if you get the chance to prep a PR, though!

**Comment by scopatz** [comment]
OK! No worries, I am not a mac user, just pointing this out.

**Comment by tschoonj** [comment]
Closed by #53
